<?php
/**
 * Tweetie.
 *
 * @copyright Wellenreiter (Wellenreiter)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Tweetie
 * @author Wellenreiter <wellenreiter01@t-online.de>.
 * @link http://www.keine.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Mon Nov 18 23:11:04 CET 2013.
 */

/**
 * Generic single item display content plugin implementation class.
 */
class Tweetie_ContentType_Item extends Tweetie_ContentType_Base_Item
{
    // feel free to extend the content type here
}

function Tweetie_Api_ContentTypes_item($args)
{
    return new Tweetie_Api_ContentTypes_itemPlugin();
}
