<?php
/**
 * Tweetie.
 *
 * @copyright Wellenreiter (Wellenreiter)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Tweetie
 * @author Wellenreiter <wellenreiter01@t-online.de>.
 * @link http://www.keine.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Mon Nov 18 23:11:04 CET 2013.
 */

/**
 * Event handler implementation class for frontend controller interaction events.
 */
class Tweetie_Listener_FrontController extends Tweetie_Listener_Base_FrontController
{
    /**
     * Listener for the `frontcontroller.predispatch` event.
     *
     * Runs before the front controller does any work.
     *
     * @param Zikula_Event $event The event instance.
     */
    public static function preDispatch(Zikula_Event $event)
    {
        parent::preDispatch($event);
    }
}
