<?php
/**
 * Tweetie.
 *
 * @copyright Wellenreiter (Wellenreiter)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Tweetie
 * @author Wellenreiter <wellenreiter01@t-online.de>.
 * @link http://www.keine.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Mon Nov 18 23:11:04 CET 2013.
 */

/**
 * The tweetieObjectState modifier displays the name of a given object's workflow state.
 * Examples:
 *    {$item.workflowState|tweetieObjectState}       {* with led icon *}
 *    {$item.workflowState|tweetieObjectState:false} {* no icon *}
 *
 * @param string  $state    Name of given workflow state.
 * @param boolean $withIcon Whether a led icon should be displayed before the name.
 *
 * @return string Enriched and translated workflow state ready for display.
 */
function smarty_modifier_tweetieObjectState($state = 'initial', $withIcon = true)
{
    $serviceManager = ServiceUtil::getManager();
    $workflowHelper = new Tweetie_Util_Workflow($serviceManager);
    $stateInfo = $workflowHelper->getStateInfo($state);

    $result = $stateInfo['text'];
    if ($withIcon === true) {
        $result = '<img src="' . System::getBaseUrl() . 'images/icons/extrasmall/' . $stateInfo['icon'] . '" width="16" height="16" alt="' . $result . '" />&nbsp;&nbsp;' . $result;
    }

    return $result;
}
