<?php
/**
 * Tweetie.
 *
 * @copyright Wellenreiter (Wellenreiter)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Tweetie
 * @author Wellenreiter <wellenreiter01@t-online.de>.
 * @link http://www.keine.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Mon Nov 18 23:11:04 CET 2013.
 */

/**
 * Installer base class.
 */
class Tweetie_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the Tweetie application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', array($this->name));
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /config/config.php file in order to reveal the error details.');
            }
            return LogUtil::registerError($returnMessage);
        }
    
        $categoryRegistryIdsPerEntity = array();
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // register persistent event handlers
        $this->registerPersistentEventHandlers();
    
        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles()); 
        HookUtil::registerProviderBundles($this->version->getHookProviderBundles());
        
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the Tweetie application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldVersion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case 1.0.0:
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s extension.', array($this->getName())));
                }
        }
    */
    HookUtil::registerProviderBundles($this->version->getHookProviderBundles());
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall Tweetie.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s extension.', array($this->getName())));
        }
    
        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s extension.', array($this->name)));
        }
    
        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers($this->name);
    
        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());
        HookUtil::unregisterProviderBundles($this->version->getHookProviderBundles());
        
        
    
        // deletion successful
        return true;
    }
    
    /**
     * Build array with all entity classes for Tweetie.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'Tweetie_Entity_Twitterparm';
    
        return $classNames;
    }
    
    /**
     * Create the default data for Tweetie.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids.
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityClass = 'Tweetie_Entity_Twitterparm';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $twitterparm1 = new \Tweetie_Entity_Twitterparm();
        
        $twitterparm1->setWorkflowState('initial');
        $twitterparm1->setConsumerKey('Twitterparm API key 1');
        $twitterparm1->setConsumerSecret('Twitterparm API secret 1');
        $twitterparm1->setAccessKey('Twitterparm access key 1');
        $twitterparm1->setAccessSecret('Twitterparm access secret 1');
        $twitterparm1->setHashtag(substr('Twitterparm hashtag', 0, 6) . ' 1'
        );
        
        
        // execute the workflow action for each entity
        $action = 'submit';
        $workflowHelper = new Tweetie_Util_Workflow($this->serviceManager);
        try {
            $success = $workflowHelper->executeAction($twitterparm1, $action);
        } catch(\Exception $e) {
            LogUtil::registerError($this->__('Sorry, but an unknown error occured during example data creation. Possibly not all data could be created properly!'));
        }
    }
    
    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core -> 
        EventUtil::registerPersistentModuleHandler('Tweetie', 'api.method_not_found', array('Tweetie_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'core.preinit', array('Tweetie_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'core.init', array('Tweetie_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'core.postinit', array('Tweetie_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'controller.method_not_found', array('Tweetie_Listener_Core', 'controllerMethodNotFound'));
    
        // front controller -> Tweetie_Listener_FrontController
        EventUtil::registerPersistentModuleHandler('Tweetie', 'frontcontroller.predispatch', array('Tweetie_Listener_FrontController', 'preDispatch'));
    
        // installer -> Tweetie_Listener_Installer
        EventUtil::registerPersistentModuleHandler('Tweetie', 'installer.module.installed', array('Tweetie_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'installer.module.upgraded', array('Tweetie_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'installer.module.uninstalled', array('Tweetie_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'installer.subscriberarea.uninstalled', array('Tweetie_Listener_Installer', 'subscriberAreaUninstalled'));
    
        // modules -> Tweetie_Listener_ModuleDispatch
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module_dispatch.postloadgeneric', array('Tweetie_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module_dispatch.preexecute', array('Tweetie_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module_dispatch.postexecute', array('Tweetie_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module_dispatch.custom_classname', array('Tweetie_Listener_ModuleDispatch', 'customClassname'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module_dispatch.service_links', array('Tweetie_Listener_ModuleDispatch', 'serviceLinks'));
    
        // mailer -> Tweetie_Listener_Mailer
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.mailer.api.sendmessage', array('Tweetie_Listener_Mailer', 'sendMessage'));
    
        // page -> Tweetie_Listener_Page
        EventUtil::registerPersistentModuleHandler('Tweetie', 'pageutil.addvar_filter', array('Tweetie_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'system.outputfilter', array('Tweetie_Listener_Page', 'systemOutputfilter'));
    
        // errors -> Tweetie_Listener_Errors
        EventUtil::registerPersistentModuleHandler('Tweetie', 'setup.errorreporting', array('Tweetie_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'systemerror', array('Tweetie_Listener_Errors', 'systemError'));
    
        // theme -> Tweetie_Listener_Theme
        EventUtil::registerPersistentModuleHandler('Tweetie', 'theme.preinit', array('Tweetie_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'theme.init', array('Tweetie_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'theme.load_config', array('Tweetie_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'theme.prefetch', array('Tweetie_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'theme.postfetch', array('Tweetie_Listener_Theme', 'postFetch'));
    
        // view -> Tweetie_Listener_View
        EventUtil::registerPersistentModuleHandler('Tweetie', 'view.init', array('Tweetie_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'view.postfetch', array('Tweetie_Listener_View', 'postFetch'));
    
        // user login -> Tweetie_Listener_UserLogin
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.ui.login.started', array('Tweetie_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.ui.login.veto', array('Tweetie_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.ui.login.succeeded', array('Tweetie_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.ui.login.failed', array('Tweetie_Listener_UserLogin', 'failed'));
    
        // user logout -> Tweetie_Listener_UserLogout
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.ui.logout.succeeded', array('Tweetie_Listener_UserLogout', 'succeeded'));
    
        // user -> Tweetie_Listener_User
        EventUtil::registerPersistentModuleHandler('Tweetie', 'user.gettheme', array('Tweetie_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'user.account.create', array('Tweetie_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'user.account.update', array('Tweetie_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'user.account.delete', array('Tweetie_Listener_User', 'delete'));
    
        // registration -> Tweetie_Listener_UserRegistration
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.ui.registration.started', array('Tweetie_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.ui.registration.succeeded', array('Tweetie_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.ui.registration.failed', array('Tweetie_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'user.registration.create', array('Tweetie_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'user.registration.update', array('Tweetie_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'user.registration.delete', array('Tweetie_Listener_UserRegistration', 'delete'));
    
        // users module -> Tweetie_Listener_Users
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.users.config.updated', array('Tweetie_Listener_Users', 'configUpdated'));
    
        // group -> Tweetie_Listener_Group
        EventUtil::registerPersistentModuleHandler('Tweetie', 'group.create', array('Tweetie_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'group.update', array('Tweetie_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'group.delete', array('Tweetie_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'group.adduser', array('Tweetie_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'group.removeuser', array('Tweetie_Listener_Group', 'removeUser'));
    
        // special purposes and 3rd party api support -> Tweetie_Listener_ThirdParty
        EventUtil::registerPersistentModuleHandler('Tweetie', 'get.pending_content', array('Tweetie_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('Tweetie', 'module.content.gettypes', array('Tweetie_Listener_ThirdParty', 'contentGetTypes'));
    }
}
