<?php
/**
 * Tweetie.
 *
 * @copyright Wellenreiter (Wellenreiter)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Tweetie
 * @author Wellenreiter <wellenreiter01@t-online.de>.
 * @link http://www.keine.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Mon Nov 18 23:11:04 CET 2013.
 */

/**
 * Version information base class.
 */
class Tweetie_Base_Version extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '1.0.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('Tweetie');
        // the module description
        $meta['description']          = $this->__('Tweetie module generated by ModuleStudio 0.6.0.');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('tweetie');
        // core requirement
        $meta['core_min']             = '1.3.5'; // requires minimum 1.3.5
        $meta['core_max']             = '1.3.9'; // not ready for 1.3.6 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
                          HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true),
                          HookUtil::PROVIDER_CAPABLE => array('enabled' => true)
/*			    'authentication' => array('version' => '1.0'),
                          'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
                          'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
*/
        );

        // permission schema
        $meta['securityschema'] = array(
            'Tweetie::' => '::',
            'Tweetie::Ajax' => '::',
            'Tweetie:ItemListBlock:' => 'Block title::',
            'Tweetie:Twitterparm:' => 'Twitterparm ID::',
        );
        // DEBUG: permission schema aspect ends


        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {
       
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.tweetie.ui_hooks.twitterparms', 'ui_hooks', __('tweetie Twitterparms Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'tweetie.ui_hooks.twitterparms.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'tweetie.ui_hooks.twitterparms.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'tweetie.ui_hooks.twitterparms.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'tweetie.ui_hooks.twitterparms.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'tweetie.ui_hooks.twitterparms.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'tweetie.ui_hooks.twitterparms.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'tweetie.ui_hooks.twitterparms.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.tweetie.filter_hooks.twitterparms', 'filter_hooks', __('tweetie Twitterparms Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'tweetie.filter_hooks.twitterparms.filter');
        $this->registerHookSubscriberBundle($bundle);

    }
}
