<?php
/**
 * Tweetie.
 *
 * @copyright Wellenreiter (Wellenreiter)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Tweetie
 * @author Wellenreiter <wellenreiter01@t-online.de>.
 * @link http://www.keine.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Mon Nov 18 23:11:04 CET 2013.
 */

/**
 * This handler class handles the page events of the Form called by the tweetie_admin_edit() function.
 * It collects common functionality required by different object types.
 */
class Tweetie_Form_Handler_Admin_Edit extends Tweetie_Form_Handler_Admin_Base_Edit
{
    // feel free to extend the base handler class here
}
