<?php
/**
 * Tweetie.
 *
 * @copyright Wellenreiter (Wellenreiter)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Tweetie
 * @author Wellenreiter <wellenreiter01@t-online.de>.
 * @link http://www.keine.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Mon Nov 18 23:11:04 CET 2013.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for twitterparm entities.
 */
class Tweetie_Entity_Validator_Twitterparm extends Tweetie_Entity_Validator_Base_Twitterparm
{
    // here you can add custom validation methods or override existing checks
}
