<?php
/**
 * Tweetie.
 *
 * @copyright Wellenreiter (Wellenreiter)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Tweetie
 * @author Wellenreiter <wellenreiter01@t-online.de>.
 * @link http://www.keine.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Mon Nov 18 23:11:04 CET 2013.
 */

/**
 * Version information implementation class.
 */
class Tweetie_Version extends Tweetie_Base_Version
{
    // custom enhancements can go here
    protected function setupHookBundles()
    {
    $bundle= new Zikula_HookManager_ProviderBundle($this->name, 'provider.tweetie.ui_hooks.tweethook', 'ui_hooks', __('Tweetie Hook Handlers'));
    $bundle-> AddServiceHandler( 'process_edit', 'Tweetie_HookHandler_Tweethook', 'process_edit', 'tweetie.tweethook');
    $this->registerHookProviderBundle($bundle);
    }
       
 }
